env: production
development:
    SITE_URL: env.dev
    SERVER_PORT: 8080
production: 
    APP_DB_USERNAME: 'Lejandro'
    APP_DB_PASSWORD: ''
    APP_DB_NAME: 'go_testing'
    APP_DB_SSLMODE: 'disable'
test:
    TEST_DB_USERNAME: 'Lejandro'
    TEST_DB_PASSWORD: ''
    TEST_DB_NAME: 'go_testing'
    TEST_DB_SSLMODE: 'disable'

